// Maisons couvertes par la génération de la base de parfums (scripts/generate-perfumes.mjs).
// ~50 marques × ~50-60 parfums ciblés ≈ 2500-3000 entrées, sans scraper Fragrantica
// (leurs CGU l'interdisent explicitement) — la base est générée par Claude à partir
// de sa connaissance générale des parfums réels et de leurs notes publiquement connues.
export const PERFUME_BRANDS: { marque: string; cible: number }[] = [
  { marque: "Chanel", cible: 60 },
  { marque: "Dior", cible: 60 },
  { marque: "Guerlain", cible: 60 },
  { marque: "Hermès", cible: 50 },
  { marque: "Yves Saint Laurent", cible: 50 },
  { marque: "Tom Ford", cible: 60 },
  { marque: "Jo Malone London", cible: 50 },
  { marque: "Le Labo", cible: 40 },
  { marque: "Byredo", cible: 40 },
  { marque: "Maison Francis Kurkdjian", cible: 40 },
  { marque: "Creed", cible: 50 },
  { marque: "Giorgio Armani", cible: 50 },
  { marque: "Prada", cible: 40 },
  { marque: "Versace", cible: 40 },
  { marque: "Gucci", cible: 40 },
  { marque: "Lancôme", cible: 40 },
  { marque: "Givenchy", cible: 40 },
  { marque: "Paco Rabanne", cible: 40 },
  { marque: "Issey Miyake", cible: 30 },
  { marque: "Thierry Mugler", cible: 30 },
  { marque: "Calvin Klein", cible: 30 },
  { marque: "Marc Jacobs", cible: 30 },
  { marque: "Viktor&Rolf", cible: 25 },
  { marque: "Carolina Herrera", cible: 30 },
  { marque: "Burberry", cible: 30 },
  { marque: "Dolce&Gabbana", cible: 40 },
  { marque: "Bvlgari", cible: 40 },
  { marque: "Cartier", cible: 30 },
  { marque: "Montblanc", cible: 25 },
  { marque: "Hugo Boss", cible: 30 },
  { marque: "Ralph Lauren", cible: 30 },
  { marque: "Narciso Rodriguez", cible: 25 },
  { marque: "Kenzo", cible: 25 },
  { marque: "Nina Ricci", cible: 25 },
  { marque: "Jean Paul Gaultier", cible: 30 },
  { marque: "Azzaro", cible: 25 },
  { marque: "Diptyque", cible: 35 },
  { marque: "Amouage", cible: 40 },
  { marque: "Xerjoff", cible: 40 },
  { marque: "Parfums de Marly", cible: 35 },
  { marque: "Nishane", cible: 30 },
  { marque: "Initio Parfums Privés", cible: 25 },
  { marque: "Mancera", cible: 35 },
  { marque: "Montale", cible: 40 },
  { marque: "Acqua di Parma", cible: 30 },
  { marque: "Bottega Veneta", cible: 20 },
  { marque: "Valentino", cible: 25 },
  { marque: "Chloé", cible: 25 },
  { marque: "Elie Saab", cible: 20 },
  { marque: "Lacoste", cible: 25 },
  { marque: "Davidoff", cible: 20 },
  { marque: "L'Occitane en Provence", cible: 20 },
];
